// Manually curated designer brand list for filtering.
const BRANDS = [
  // Avant-garde
  "Maison Margiela",
  "Margiela",
  "MM6",
  "Yohji Yamamoto",
  "Comme des Garçons",
  "Issey Miyake",
  "Pleats Please",
  "Homme Plissé",
  "Undercover",
  "Number Nine",
  "Kosuke Tsumura",
  "Final Home",
  "Needles",
  "Engineered Garments",
  "Kapital",
  "Visvim",
  "Sacai",
  "Junya Watanabe",
  "Noir Kei Ninomiya",
  "Maison Mihara Yasuhiro",
  "Mihara Yasuhiro",
  "If Six was Nine",
  "By Joshua Jamal",
  "Joshua Jamal",

  // Belgian / Antwerp
  "Ann Demeulemeester",
  "Dries Van Noten",
  "Raf Simons",
  "Walter Van Beirendonck",
  "Dirk Bikkembergs",
  "Dirk Schönberger",
  "A.F. Vandevorst",
  "Haider Ackermann",

  // French
  "Helmut Lang",
  "Jean Paul Gaultier",
  "Thierry Mugler",
  "Claude Montana",
  "Azzedine Alaïa",
  "Alaia",
  "Courrèges",
  "Lanvin",
  "Sonia Rykiel",
  "Kenzo",
  "Cacharel",
  "Carven",
  "A.P.C.",
  "Jacquemus",
  "Isabel Marant",
  "Ami",
  "Ami Paris",
  "Vetements",
  "Vêtements",
  "Y/PROJECT",
  "Matieres Fecales",
  "Matières Fécales",
  "Enfants Riches Deprimes",
  "Enfants Riches Déprimés",
  "Alain Paul",
  "Lanvin",

  // French luxury
  "Chanel",
  "Dior",
  "Christian Dior",
  "Saint Laurent",
  "Yves Saint Laurent",
  "YSL",
  "Givenchy",
  "Celine",
  "Céline",
  "Loewe",
  "Louis Vuitton",
  "Hermès",
  "Balenciaga",
  "Courrèges",
  "Cartier",
  "Goyard",
  "Schiaparelli",
  "Mugler",
  "Lemaire",
  "Christian Louboutin",
  "Jacques Marie Mage",


  // Italian
  "Prada",
  "Miu Miu",
  "Gucci",
  "Versace",
  "Gianni Versace",
  "Dolce & Gabbana",
  "Roberto Cavalli",
  "Valentino",
  "Fendi",
  "Bottega Veneta",
  "Marni",
  "Jil Sander",
  "Giorgio Armani",
  "Emporio Armani",
  "Azzaro",
  "Berluti",
  "Ferragamo",
  "Loro Piana",
  "Moncler",


  // British
  "Vivienne Westwood",
  "Alexander McQueen",
  "McQ",
  "Burberry",
  "Hussein Chalayan",
  "John Galliano",
  "Christopher Kane",
  "Martine Rose",
  "Jonathan Anderson",
  "JW Anderson",
  "Wales Bonner",

  // American
  "Rick Owens",
  "Helmut Lang",
  "Tom Ford",
  "Marc Jacobs",
  "Willy Chavarria",
  "Marking Distance",
  "The Row",
  "Thom Browne",

  // Miscellaneous
  "Stone Island",
  "CP Company",
  "Chrome Hearts",
  "Iris Van Herpen",
  "Carol Christian Poell",
  "Coperni",

  // Other archive staples
  "Acne Studios",
  "Acne",
  "A.L.C.",
  "Ports 1961",
  "Jean-Charles de Castelbajac",
  "JCDC",
  "Veronique Branquinho",
  "Bernhard Willhelm",
  "Damir Doma",
  "Julius",
  "Boris Bidjan Saberi",
  "Attachment",
  "Obscur",
  "Balmain",
  "Veneda Carter",
  "Kiko Kostadinov",
  "424",
  "Charles Jeffrey Loverboy",
  "Alexander Digenova",
  "Heliot Emil",
  "Our Legacy",
];

export default BRANDS;