import { Analytics } from "@vercel/analytics/react";
import LayoutClient from "./components/LayoutClient";
import Footer from "./components/Footer";
import { getActiveStores } from "./lib/stores.js";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const stores = await getActiveStores();
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <LayoutClient stores={stores}>{children}</LayoutClient>
        <Footer />
      </body>
      <Analytics />
    </html>
  );
}
